@startuml
skinparam linetype ortho
class "ncurses-dev" as ncurses_dev {
}
class "libformw" as libformw {
}
class "ncurses-terminfo-base" as terminfo_base {
}
class "so:libc.musl-x86_64.so.1" as libc {
}
class "so:libncursesw.so.6" as libncursesw {
}
ncurses_dev --> libformw
libformw --> terminfo_base
libformw --> libc
libformw --> libncursesw
class "libmenuw" as libmenuw {
}
ncurses_dev --> libmenuw
libmenuw --> terminfo_base
libmenuw --> libc
libmenuw --> libncursesw
class "libncurses++" as libncursespp {
}
ncurses_dev --> libncursespp
libncursespp --> terminfo_base
libncursespp --> libc
libncursespp --> libformw
libncursespp --> "so:libgcc_s.so.1"
libncursespp --> "so:libmenuw.so.6"
libncursespp --> libncursesw
libncursespp --> "so:libpanelw.so.6"
libncursespp --> "so:libstdc++.so.6"
class "libncursesw" as libncursesw {
}
ncurses_dev --> libncursesw
libncursesw --> terminfo_base
libncursesw --> libc
class "libpanelw" as libpanelw {
}
ncurses_dev --> libpanelw
libpanelw --> terminfo_base
libpanelw --> libc
libpanelw --> libncursesw
class "pkgconfig" as pkgconfig {
}
ncurses_dev --> pkgconfig
@enduml